version: '2.2'
services:
  nginx:
    image: nginx
    container_name: nginx
    ports:
      - 80:80
    networks:
      - elastic
    volumes:
      - ./config/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./config/nginx/proxy_params.conf:/etc/nginx/proxy_params.conf:ro

networks:
  elastic:
    driver: bridge
