version: '2.2'

services:
  metricbeat:
    container_name: metricbeat
    image: docker.elastic.co/beats/metricbeat:7.15.2
    command: -e --strict.perms=false
    user: "0"
    volumes: 
      - ./config/metricbeat.yml:/usr/share/metricbeat/metricbeat.yml:ro
      - certs:/usr/share/metricbeat/certificates:ro
    networks:
      - elastic

volumes: 
  certs:
    driver: local

networks:
  elastic:
    driver: bridge
