version: '2.2'
services:
  filebeat:
    image: docker.elastic.co/beats/filebeat:7.16.0
    container_name: filebeat
    command: -e --strict.perms=false
    user: "0"
    environment:
      - BEAMLINE=mybeamline
    volumes: 
      - ./config/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - certs:/usr/share/filebeat/certificates:ro
      - filebeat_data:/usr/share/filebeat/data
      - ./logs:/logs
    networks:
      - elastic

volumes: 
  certs:
    driver: local
  filebeat_data:
    driver: local

networks:
  elastic:
    driver: bridge
