# Kibana configuration for docker target
server.host: "0"
server.name: kib01
server.publicBaseUrl: http://localhost:5601
server.shutdownTimeout: "5s"
elasticsearch.hosts: [ "http://es01:9200", "http://es02:9200", "http://es03:9200" ]
monitoring.ui.container.elasticsearch.enabled: true

elasticsearch.username: "kibana_system"
elasticsearch.password: "DontUse"