version: '2.2'
services:
  kibana:
    image: docker.elastic.co/kibana/kibana:7.16.0
    container_name: kib01
    ports:
      - "5601:5601"
    volumes:
      - ./config/kibana.yml:/usr/share/kibana/config/kibana.yml
    networks:
      - elastic

networks:
  elastic:
    driver: bridge