version: '2.2'
services:
  kibana:
    image: docker.elastic.co/kibana/kibana:7.15.2
    container_name: kib01
    ports:
      - "5601:5601"
    volumes:
      - ./config/kibana.yml:/usr/share/kibana/config/kibana.yml:ro
      - certs:/usr/share/kibana/config/certificates:ro
    networks:
      - elastic

volumes:
  certs:
    driver: local

networks:
  elastic:
    driver: bridge
