# Kibana configuration for docker target
server.host: "0"

server.shutdownTimeout: "5s"
elasticsearch.hosts: [ "https://es01:9200", "https://es02:9200", "https://es03:9200" ]

monitoring.ui.container.elasticsearch.enabled: true

elasticsearch.username: "kibana"
elasticsearch.password: "HR8cKKGhVQMfvyOXo95n" 

elasticsearch.ssl.certificateAuthorities: /usr/share/kibana/config/certificates/ca/ca.crt
