version: '2.2'
services:
  kib01:
    image: docker.elastic.co/kibana/kibana:7.16.0
    container_name: kib01
    ports:
      - "5601:5601"
    volumes:
      - ./config/kibana.yml:/usr/share/kibana/config/kibana.yml:ro
      - certs:/usr/share/kibana/config/certificates:ro
    environment:
      - SERVER_NAME=kib01
      # - SERVER_SSL_ENABLED=true
      # - SERVER_SSL_CERTIFICATE=/usr/share/kibana/config/certificates/kib01/kib01.crt
      # - SERVER_SSL_KEY=/usr/share/kibana/config/certificates/kib01/kib01.key
    networks:
      - elastic
  kib02:
    image: docker.elastic.co/kibana/kibana:7.16.0
    container_name: kib02
    ports:
      - "5602:5601"
    volumes:
      - ./config/kibana.yml:/usr/share/kibana/config/kibana.yml:ro
      - certs:/usr/share/kibana/config/certificates:ro
    environment:
      - SERVER_NAME=kib02
      # - SERVER_SSL_ENABLED=true
      # - SERVER_SSL_CERTIFICATE=/usr/share/kibana/config/certificates/kib02/kib02.crt
      # - SERVER_SSL_KEY=/usr/share/kibana/config/certificates/kib02/kib02.key
    networks:
      - elastic

volumes:
  certs:
    driver: local

networks:
  elastic:
    driver: bridge
