version: '2.2'

services:
  create_keystore:
    container_name: create_keystore
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.2
    command: >
      bash -c '
        if [ ! -f "/usr/share/elasticsearch/config/elasticsearch.keystore" ] ; then
          bin/elasticsearch-keystore create
          echo "certificates-pass" | bin/elasticsearch-keystore add --stdin xpack.security.transport.ssl.keystore.secure_password
          echo "certificates-pass" | bin/elasticsearch-keystore add --stdin xpack.security.transport.ssl.truststore.secure_password
        fi
        bin/elasticsearch-keystore list
        '
    #user: "0"
    working_dir: /usr/share/elasticsearch
    volumes: 
      - './config:/usr/share/elasticsearch/config'

volumes: 
  certs:
    driver: local
