version: '2.2'

services:
  create_certs:
    container_name: create_certs
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.2
    command: >
      bash -c '
        bin/elasticsearch-certutil ca --out /certs/elastic-stack-ca.p12 --pass "ca-pass" 
        bin/elasticsearch-certutil cert --ca /certs/elastic-stack-ca.p12 --ca-pass "ca-pass" --out /certs/elastic-certificates.p12 --pass "certificates-pass" 
        chown -R 1000:0 /certs
        '
    user: "0"
    working_dir: /usr/share/elasticsearch
    volumes: 
      - certs:/certs

volumes: 
  certs:
    driver: local