# Kibana configuration for docker target
server.host: "0"

server.shutdownTimeout: "5s"
elasticsearch.hosts: [ "https://es01:9200", "https://es02:9200", "https://es03:9200" ]

# Use metricbeat for monitoring as preconised from 7.16.0
monitoring.ui.container.elasticsearch.enabled: true
monitoring.kibana.collection.enabled: false

elasticsearch.username: "kibana_system"
elasticsearch.password: "DontUse" 

elasticsearch.ssl.certificateAuthorities: /usr/share/kibana/config/certificates/ca/ca.crt
