output.elasticsearch:
  hosts: [ "es01:9200", "es02:9200", "es03:9200" ]
  protocol: "https"
  username: "metricbeat_writer"
  password: "DontUse"
  ssl:
    certificate_authorities:  ["/usr/share/metricbeat/certificates/ca/ca.crt"]
    verification_mode: "certificate"

setup.kibana:
  host: "kib01:5601" 
  username: "metricbeat_setup"
  password: "DontUse"

metricbeat.modules:
  - module: logstash
    xpack.enabled: true
    metricsets: 
      - node
      - node_stats
    period: 10s
    hosts: ["logstash:9600"]
